// <auto-generated />
using System;
using ECom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECom.Data.Migrations
{
    [DbContext(typeof(EComContext))]
    [Migration("20210507060221_Seed-Customers-And-Addresses")]
    partial class SeedCustomersAndAddresses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECore.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Lagos",
                            CustomerId = 1,
                            Street = "Adeniji Adele",
                            StreetNumber = "42A"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Port Harcourt",
                            CustomerId = 2,
                            Street = "Tombia",
                            StreetNumber = "30"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Abuja",
                            CustomerId = 3,
                            Street = "Oliver Tambo",
                            StreetNumber = "5"
                        },
                        new
                        {
                            AddressId = 4,
                            City = "Ibadan",
                            CustomerId = 4,
                            Street = "Ojo'badan",
                            StreetNumber = "26"
                        },
                        new
                        {
                            AddressId = 5,
                            City = "Uyo",
                            CustomerId = 5,
                            Street = "Emco",
                            StreetNumber = "15B"
                        },
                        new
                        {
                            AddressId = 6,
                            City = "Abuja",
                            CustomerId = 6,
                            Street = "Abbey",
                            StreetNumber = "120"
                        },
                        new
                        {
                            AddressId = 7,
                            City = "Lagos",
                            CustomerId = 7,
                            Street = "Bandara",
                            StreetNumber = "92"
                        },
                        new
                        {
                            AddressId = 8,
                            City = "Lagos",
                            CustomerId = 8,
                            Street = "Altgasse",
                            StreetNumber = "8"
                        },
                        new
                        {
                            AddressId = 9,
                            City = "Port Harcourt",
                            CustomerId = 9,
                            Street = "Osu",
                            StreetNumber = "21"
                        },
                        new
                        {
                            AddressId = 10,
                            City = "Uyo",
                            CustomerId = 10,
                            Street = "Hampton",
                            StreetNumber = "35"
                        },
                        new
                        {
                            AddressId = 11,
                            City = "Lagos",
                            CustomerId = 11,
                            Street = "Marina",
                            StreetNumber = "103"
                        },
                        new
                        {
                            AddressId = 12,
                            City = "Ibadan",
                            CustomerId = 12,
                            Street = "Marktgasse",
                            StreetNumber = "40C"
                        },
                        new
                        {
                            AddressId = 13,
                            City = "Lagos",
                            CustomerId = 13,
                            Street = "Havelska",
                            StreetNumber = "72"
                        },
                        new
                        {
                            AddressId = 14,
                            City = "Uyo",
                            CustomerId = 14,
                            Street = "F Line",
                            StreetNumber = "31"
                        });
                });

            modelBuilder.Entity("ECore.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ECore.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Chris",
                            LastName = "Imoni"
                        },
                        new
                        {
                            CustomerId = 4,
                            FirstName = "Lawrence",
                            LastName = "Nwachukwu"
                        },
                        new
                        {
                            CustomerId = 5,
                            FirstName = "Abubakar",
                            LastName = "Mohammed"
                        },
                        new
                        {
                            CustomerId = 6,
                            FirstName = "Esther",
                            LastName = "Adesokan"
                        },
                        new
                        {
                            CustomerId = 7,
                            FirstName = "Jadesola",
                            LastName = "Akande"
                        },
                        new
                        {
                            CustomerId = 8,
                            FirstName = "Emem",
                            LastName = "Nkamare"
                        },
                        new
                        {
                            CustomerId = 9,
                            FirstName = "Gloria",
                            LastName = "Lawal"
                        },
                        new
                        {
                            CustomerId = 10,
                            FirstName = "Toyin",
                            LastName = "Ogunjobi"
                        },
                        new
                        {
                            CustomerId = 11,
                            FirstName = "Bayo",
                            LastName = "Ogundele"
                        },
                        new
                        {
                            CustomerId = 12,
                            FirstName = "Nawok",
                            LastName = "Gotau"
                        },
                        new
                        {
                            CustomerId = 13,
                            FirstName = "Abiodun",
                            LastName = "Alonge"
                        },
                        new
                        {
                            CustomerId = 14,
                            FirstName = "Chinenye",
                            LastName = "Obiano"
                        });
                });

            modelBuilder.Entity("ECore.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECore.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShipperId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShipperId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ECore.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECore.Models.Shipper", b =>
                {
                    b.Property<int>("ShipperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShipperName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipperId");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("ECore.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ECore.Models.Address", b =>
                {
                    b.HasOne("ECore.Models.Customer", null)
                        .WithOne("Address")
                        .HasForeignKey("ECore.Models.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ECore.Models.Order", b =>
                {
                    b.HasOne("ECore.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECore.Models.OrderDetail", b =>
                {
                    b.HasOne("ECore.Models.Customer", "Customer")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECore.Models.Shipper", "Shipper")
                        .WithMany()
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Shipper");
                });

            modelBuilder.Entity("ECore.Models.Product", b =>
                {
                    b.HasOne("ECore.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECore.Models.Shipper", null)
                        .WithMany("Products")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECore.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ECore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECore.Models.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("OrderDetails");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ECore.Models.Shipper", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECore.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
